# Generated by Django 4.0.1 on 2022-01-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth_year',
        ),
        migrations.AddField(
            model_name='person',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
