# Generated by Django 4.0.1 on 2022-01-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_remove_person_birth_year_person_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth',
            field=models.DateField(),
        ),
    ]
